#include <SPI.h>
#include <SD.h>

word softwareversion = 'Alpha 1.0 Test Stage';

File file;

void startup() {
  Serial.begin(9600);
  Serial.println();
  Serial.println("Initialising SD Card...");
  if (!SD.begin()) {
    Serial.println("SD Card Communications Failure!");
    Serial.println("Without SD Card, This Unit Cannot Hold Memory and, as a result, cannot function properly!");
    Serial.println("To retry SD Communications, reset the arduino, or connect power to pin D2");
    while (digitalRead(2) == 0) { }
    startup();
  }
  Serial.println("Initialised. Writing to file Initialisations_Test_File.txt...");
  file = SD.open("INITIALISATIONS_TEST_FILE.TXT", FILE_WRITE);
  file.print("Arduino Uno R3 Board: Software version - ");
  file.println(softwareversion);
  file.close();
  file = SD.open("INITIALISATIONS_TEST_FILE.TXT",FILE_READ);
  delay(100);
  file.close();
  Serial.println("File write Complete");
  Serial.println("Pausing to allow Sensors to Start...");
  delay(3000);
  Serial.println("Pause Complete. Saving Sensor readings for Initial Randomisation...");
  file = SD.open("Readings_1.txt", FILE_WRITE);
  var = digitalRead(2);
  file.println(var);
  var = digitalRead(3);
  file.println(var);
  var = digitalRead(4);
  file.println(var);
  var = digitalRead(5);
  file.println(var);
  var = digitalRead(6);
  file.println(var);
  var = digitalRead(7);
  file.println(var);
  var = digitalRead(8);
  file.println(var);
  var = digitalRead(9);
  file.println(var);
  var = digitalRead(10);
  file.println(var);
  var = digitalRead(11);
  file.println(var);
  var = digitalRead(12);
  file.println(var);
  var = digitalRead(13);
  file.println(var);
  var = analogRead(A0);
  file.println(var);
  var = analogRead(A1);
  file.println(var);
  var = analogRead(A2);
  file.println(var);
  var = analogRead(A3);
  file.println(var);
  var = analogRead(A4);
  file.println(var);
  var = analogRead(A5);
  file.println(var);
  file.close();
  delay(500);
  file = SD.open("Readings_2.TXT", FILE_WRITE);
  var = digitalRead(2);
  file.println(var);
  var = digitalRead(3);
  file.println(var);
  var = digitalRead(4);
  file.println(var);
  var = digitalRead(5);
  file.println(var);
  var = digitalRead(6);
  file.println(var);
  var = digitalRead(7);
  file.println(var);
  var = digitalRead(8);
  file.println(var);
  var = digitalRead(9);
  file.println(var);
  var = digitalRead(10);
  file.println(var);
  var = digitalRead(11);
  file.println(var);
  var = digitalRead(12);
  file.println(var);
  var = digitalRead(13);
  file.println(var);
  var = analogRead(A0);
  file.println(var);
  var = analogRead(A1);
  file.println(var);
  var = analogRead(A2);
  file.println(var);
  var = analogRead(A3);
  file.println(var);
  var = analogRead(A4);
  file.println(var);
  var = analogRead(A5);
  file.println(var);
  file.close();
  delay(500);
  file = SD.open("Readings_3.TXT", FILE_WRITE);
  var = digitalRead(2);
  file.println(var);
  var = digitalRead(3);
  file.println(var);
  var = digitalRead(4);
  file.println(var);
  var = digitalRead(5);
  file.println(var);
  var = digitalRead(6);
  file.println(var);
  var = digitalRead(7);
  file.println(var);
  var = digitalRead(8);
  file.println(var);
  var = digitalRead(9);
  file.println(var);
  var = digitalRead(10);
  file.println(var);
  var = digitalRead(11);
  file.println(var);
  var = digitalRead(12);
  file.println(var);
  var = digitalRead(13);
  file.println(var);
  var = analogRead(A0);
  file.println(var);
  var = analogRead(A1);
  file.println(var);
  var = analogRead(A2);
  file.println(var);
  var = analogRead(A3);
  file.println(var);
  var = analogRead(A4);
  file.println(var);
  var = analogRead(A5);
  file.println(var);
  file.close();
  delay(500);
  file = SD.open("Readings_4.TXT", FILE_WRITE);
  var = digitalRead(2);
  file.println(var);
  var = digitalRead(3);
  file.println(var);
  var = digitalRead(4);
  file.println(var);
  var = digitalRead(5);
  file.println(var);
  var = digitalRead(6);
  file.println(var);
  var = digitalRead(7);
  file.println(var);
  var = digitalRead(8);
  file.println(var);
  var = digitalRead(9);
  file.println(var);
  var = digitalRead(10);
  file.println(var);
  var = digitalRead(11);
  file.println(var);
  var = digitalRead(12);
  file.println(var);
  var = digitalRead(13);
  file.println(var);
  var = analogRead(A0);
  file.println(var);
  var = analogRead(A1);
  file.println(var);
  var = analogRead(A2);
  file.println(var);
  var = analogRead(A3);
  file.println(var);
  var = analogRead(A4);
  file.println(var);
  var = analogRead(A5);
  file.println(var);
  file.close();
  delay(500);
  Serial.println("Sensor SD save complete");
}
