#include <Wire.h>  // Comes with Arduino IDE
#include <LiquidCrystal_I2C.h>

LiquidCrystal_I2C lcd(0x3F,20,4);  // Set the LCD I2C address
int delayVal = 200;

void setup() {
  Serial.begin(9600);
  Wire.begin();
  lcd.begin(20,4);
  lcd.backlight();
}

void loop() {
  lcd.setCursor(19,1);
  lcd.print("T");
  delay(delayVal);
  lcd.setCursor(18,1);
  lcd.print("Th");
  delay(delayVal);
  lcd.setCursor(17,1);
  lcd.print("Thi");
  delay(delayVal);
  lcd.setCursor(16,1);
  lcd.print("This");
  delay(delayVal);
  lcd.setCursor(15,1);
  lcd.print("This ");
  delay(delayVal);
  lcd.setCursor(14,1);
  lcd.print("This i");
  delay(delayVal);
  lcd.setCursor(13,1);
  lcd.print("This is");
  delay(delayVal);
  lcd.setCursor(12,1);
  lcd.print("This is ");
  delay(delayVal);
  lcd.setCursor(11,1);
  lcd.print("This is a");
  delay(delayVal);
  lcd.setCursor(10,1);
  lcd.print("This is a ");
  delay(delayVal);
  lcd.setCursor(9,1);
  lcd.print("This is a t");
  delay(delayVal);
  lcd.setCursor(8,1);
  lcd.print("This is a te");
  delay(delayVal);
  lcd.setCursor(7,1);
  lcd.print("This is a tes");
  delay(delayVal);
  lcd.setCursor(6,1);
  lcd.print("This is a test");
  delay(delayVal);
  lcd.setCursor(5,1);
  lcd.print("This is a test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(4,1);
  lcd.print("This is a test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(3,1);
  lcd.print("This is a test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(2,1);
  lcd.print("This is a test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(1,1);
  lcd.print("This is a test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("This is a test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("his is a test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("is is a test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("s is a test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print(" is a test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("is a test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("s a test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print(" a test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("a test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print(" test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("test!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("st!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("t!");
  delay(delayVal);
  lcd.clear();
  lcd.setCursor(0,1);
  lcd.print("!");
  delay(delayVal);
  lcd.clear();
  delay(delayVal);
}
